INSERT INTO Sentences
  (text, language_key)
VALUES
  ('I have lost my passport','EN'),
  ('Eu perdi meu passaporte','PT'),
  ('मैंने अपना पासपोर्ट खो दिया है','HI'),
  ('mainne apana paasaport kho diya hai','HI'),
  ('Someone stole my money', 'EN'),
  ('Alguém roubou meu dinheiro','PT'),
  ('किसी ने मेरा पैसा चुरा लिया','HI'),
  ('kisee ne mera paisa chura liya','HI'),
  ('Help','EN'),
  ('Socorro','PT'),
  ('मदद','HI'),
  ('madad','HI'),
  ('May I have the bill','EN'),
  ('Pode trazer a conta','PT'),
  ('क्या मुझे बिल मिल सकता है','HI'),
  ("kya mujhe bil mil sakata hai",'HI'),
  ('I would like dessert','EN'),
  ('Eu gostaria de sobremesa','PT'),
  ('मैं मिठाई चाहूंगा','HI'),
  ('main mithaee chaahoonga','HI'),
  ('I would like to order', 'EN'),
  ('Eu gostaria de pedir','PT'),
  ('मैं फरमाइश करना चाहता हूँ','HI'),
  ('main pharamaish karana chaahata hoon','HI'),
  ('May I see a menu', 'EN'),
  ('Posso ver um menu','PT'),
  ('क्या मुझे एक मेनू मिल सकताा है','HI'),
  ('kya mujhe ek menu mil sakata  hai','HI'),
  ('I would like a drink','EN'),
  ('Quero uma bebida','PT'),
  ('मुझे ड्रिंक चाहिए','HI'),
  ('mujhe drink chaahie','HI'),
  ('I would like some water','EN'),
  ('Eu gostaria de um pouco de água','PT'),
  ('थोडा पानी पीना चाहूँगा।','HI'),
  ('thoda paanee peena chaahoonga','HI'),
  ('A table for two','EN'),
  ('Uma mesa para dois','PT'),
  ('हम दो के लिए एक मेज','HI'),
  ('hum do ke lie ek mej','HI'),
  ('A table for four','EN'),
  ('Uma mesa para quatro','PT'),
  ('हम चार के लिए एक मेज।','HI'),
  ('hum chaar ke lie ek mej','HI'),
  ('How far is it to the airport','EN'),
  ('A que distância fica do aeroporto','PT'),
  ('हवाई अड्डे से कितनी दूर है','HI'),
  ('havaee adde se kitanee door hai','HI'),
  ('How far is it to the hotel','EN'),
  ('Qual é a distância para o hotel','PT'),
  ('यहां से होटल कितनी दूरी पर हैै','HI'),
  ('yahaan se hotal kitanee dooree par hai','HI'),
  ('How do you get to the airport','EN'),
  ('Como você chega ao aeroporto','PT'),
  ('हवाई अड्डे तक कैसे पहुंचेंगे','HI'),
  ('havaee adde tak kaise pahunchenge','HI'),
  ('How do you get to the hotel','EN'),
  ('Como você chega ao hotel','PT'),
  ('आप होटल में कैसे पहुँचेंगेै','HI'),
  ('aap hotal mein kaise pahunchenge','HI'),
  ('Where is the bank','EN'),
  ('Onde é o Banco','PT'),
  ('बैंक कहाँ हैै','HI'),
  ('bank kahaan hai','HI'),
  ('Where can I find a restaurant','EN'),
  ('Onde posso encontrar um restaurante','PT'),
  ('मुझे एक रेस्तरां कहां मिल सकता है','HI'),
  ('mujhe ek restaraan kahaan mil sakata hai','HI'),
  ('Where is the hospital','EN'),
  ('Onde fica o hospital','PT'),
  ('अस्पताल कहाँ है','HI'),
  ('aspataal kahaan hai','HI'),
  ('Where can I find a grocery store','EN'),
  ('Onde posso encontrar uma mercearia','PT'),
  ('मुझे किराने की दुकान कहां मिल सकती है','HI'),
  ('mujhe kiraane kee dukaan kahaan mil sakatee hai','HI'),
  ('How do I call down to the front desk','EN'),
  ('Como faço para ligar para a recepção','PT'),
  ('मैं फ्रंट डेस्क पर कैसे कॉल करूं','HI'),
  ('main phrant desk par kaise kol karoon','HI'),
  ('How do I call for room service','EN'),
  ('Como faço para ligar para o serviço de quarto','PT'),
  ('मैं रूम सर्विस के लिए कैसे कॉल करूं','HI'),
  ('main room sarvis ke lie kaise kol karoon','HI'),
  ('My room is messy, and I would like it cleaned','EN'),
  ('Meu quarto está bagunçado e eu gostaria de limpá-lo','PT'),
  ('मेरा कमरा गन्दा है, और मैं चाहूंगा कि यह साफ हो जाए','HI'),
  ('mera kamara ganda hai, aur main chaahoonga ki yah saaph ho jae','HI'),
  ('My room needs towels','EN'),
  ('Meu quarto precisa de toalhas','PT'),
  ('मेरे कमरे में तौलिये की जरूरत है','HI'),
  ('mere kamare mein tauliye kee jaroorat hai','HI'),
  ('Is there free breakfast','EN'),
  ('Tem café da manhã grátis','PT'),
  ('मक्या मुफ्त का नाश्ता है','HI'),
  ('kya mupht ka naashta hai','HI'),
  ('How do I access the Internet','EN'),
  ('Como eu acesso a Internet','PT'),
  ('मैं इंटरनेट का उपयोग कैसे करूं','HI'),
  ('main intaranet ka upayog kaise karoon','HI'),
  ('Where are the elevators','EN'),
  ('Onde estão os elevadores','PT'),
  ('लिफ्ट कहां हैं','HI'),
  ('lipht kahaan hain','HI'),
  ('What floor am I on','EN'),
  ('Em que andar estou','PT'),
  ('मैं किस मंजिल पर हूँ','HI'),
  ('main kis manjil par hoon','HI'),
  ('How many beds are in the room','EN'),
  ('Quantas camas estão no quarto','PT'),
  ('इस कमरे में कितने बिस्तर हैंँ','HI'),
  ('is kamare mein kitane bistar hain','HI'),
  ('Does the room have a bathroom','EN'),
  ('O quarto tem banheiro','PT'),
  ('क्या कमरे में बाथरूम है','HI'),
  ('kya kamare mein baatharoom hai','HI'),
  ('I don’t understand','EN'),
  ('Eu não entendo','PT'),
  ('मैं नहीं समझता','HI'),
  ('main nahin samajhata','HI'),
  ('I would like to go to the airport','EN'),
  ('Eu gostaria de ir ao aeroporto','PT'),
  ('मैं एयरपोर्ट जाना चाहूंगा','HI'),
  ('main eyaraport jaana chaahoonga','HI'),
  ('I would like to go to the the mall','EN'),
  ('Eu gostaria de ir ao shopping','PT'),
  ('मैं मॉल जाना चाहूंगा','HI'),
  ('main mol jaana chaahoonga','HI'),
  ('I would like to go to the the hotel','EN'),
  ('Eu gostaria de ir ao hotel','PT'),
  ('मैं होटल जाना चाहूंगाा','HI'),
  ('main hotal jaana chaahoonga','HI'),
  ('I would like to go to work','EN'),
  ('Eu gostaria de ir trabalhar','PT'),
  ('मैं काम पर जाना चाहूंगा','HI'),
  ('main kaam par jaana chaahoonga','HI'),
  ('I would like to go eat','EN'),
  ('Eu gostaria de ir comer','PT'),
  ('मैं खाना खाने जाना चाहूंगा','HI'),
  ('main khaana khaane jaana chaahoonga','HI'),
  ('Do you know where this hotel is','EN'),
  ('Você sabe onde fica este hotel','PT'),
  ('क्या आप जानते हैं कि यह होटल कहाँ है','HI'),
  ('kya aap jaanate hain ki yah hotal kahaan hai','HI'),
  ('Where can I find a taxi','EN'),
  ('Onde posso encontrar um táxi','PT'),
  ('मुझे टैक्सी कहाँ मिल सकती हैा','HI'),
  ('mujhe taiksee kahaan mil sakatee hai','HI'),
  ('Where is the bus stop','EN'),
  ('Onde é o ponto de ônibus','PT'),
  ('बस स्टॉप कहा है','HI'),
  ('bus stop kaha hai','HI'),
  ('Where is the currency exchange','EN'),
  ('Onde está a troca de moeda','PT'),
  ('मुद्रा विनिमय कहां है','HI'),
  ('mudra vinimay kahaan hai','HI'),
  ('Do you have a map','EN'),
  ('Você tem um mapa','PT'),
  ('क्या तुम्हारे पास नक्शा हैं','HI'),
  ('kya tumhaare paas naksha hai','HI'),
  ('I am staying at a hotel','EN'),
  ('Eu estou hospedado em um hotel','PT'),
  ('मैं एक होटल में ठहरा हूँ','HI'),
  ('main ek hotal mein thahara hoon','HI'),
  ('I am visiting family','EN'),
  ('Eu estou visitando a família','PT'),
  ('मैं अपने परिवार सेा मिलनेा जा रहा हूै','HI'),
  ('main apne parivaar se milne ja raha hoon.','HI'),
  ('I will be here for a few days','EN'),
  ('Eu estarei aqui por alguns dias','PT'),
  ('मैं कुछ दिनों के लिए यहां रहूंगा।','HI'),
  ('main kuchh dinon ke lie yahaan rahoonga','HI'),
  ('I will be here for a week','EN'),
  ('Eu estarei aqui por uma semana','PT'),
  ('मैं एक सप्ताह के लिए यहां रहूंगा।','HI'),
  ('main ek saptaah ke lie yahaan rahoonga','HI'),
  ('I will be here for a few weeks','EN'),
  ('Eu estarei aqui por algumas semanas','PT'),
  ('मैं कुछ हफ्तों के लिए यहां रहूंगा।','HI'),
  ('main kuchh haphton ke lie yahaan rahoonga','HI'),
  ('I am traveling for work','EN'),
  ('Eu estou viajando para o trabalho','PT'),
  ('क्मैं काम के लिए यात्रा कर रहा हूैं','HI'),
  ('main kaam ke lie yaatra kar raha hoon','HI'),
  ('I am traveling for leisure','EN'),
  ('Eu estou viajando a lazer','PT'),
  ('मैं अवकाश के लिए यात्रा कर रहा हूं','HI'),
  ('main avakaash ke lie yaatra kar raha hoon','HI'),
  ('I have a connecting flight','EN'),
  ('Eu tenho um voo de conexão','PT'),
  ('मेरी कनेक्टिंग फ्लाइट है','HI'),
  ('meree connecting flight hai','HI')
