INSERT INTO Sentences
  (text, language_key)
VALUES
  ('I’d like to order room service, please','EN'),
  ('Eu gostaria de pedir serviço de quarto, por favor','PT'),
  ('क्यमुझे रूम सर्विस ऑर्डर करना है, कृपया','HI'),
  ('mujhe room sarvis ordar karana hai, krpaya','HI'),
  ('I would like to have a wake-up call at 5:30', 'EN'),
  ('Eu gostaria de ter uma chamada de despertar às 5:30','PT'),
  ('मैं 5:30 बजे उठना चाहूंगा','HI'),
  ('main 5:30 baje uthana chaahoonga','HI'),
  ('What is the check-out time at this hotel','EN'),
  ('Qual é o horário do check-out neste hotel','PT'),
  ('इस होटल में चेक-आउट का समय क्या है','HI'),
  ('is hotal mein chek-aaut ka samay kya hai','HI'),
  ('Do you have a bus service to and from the airport','EN'),
  ('Você tem um serviço de ônibus para o aeroporto','PT'),
  ('क्या आपके पास हवाई अड्डे से जाने और आने के लिए बस सेवा है','HI'),
  ("kya aapake paas havaee adde se jaane aur aane ke lie bas seva hai",'HI'),
  ('Could you show me my room','EN'),
  ('Você poderia me mostrar o meu quarto','PT'),
  ('क्या आप मुझे मेरा कमरा दिखा सकते हैैं','HI'),
  ('kya aap mujhe mera kamara dikha sakate hain?','HI'),
  ('Where is the elevator', 'EN'),
  ('Onde fica o elevador','PT'),
  ('लिफ्ट कहाँ हैै','HI'),
  ('lipht kahaan hai','HI'),
  ('Where is the emergency exit', 'EN'),
  ('Onde é a saída de emergência','PT'),
  ('आपातकालीन निकास कहां पर हैै','HI'),
  ('aapaatakaaleen nikaas kahaan par hai','HI'),
  ('The bed sheets are dirty','EN'),
  ('Os lençóis da cama são sujos','PT'),
  ('बिस्तर की चादरें गंदी हैै','HI'),
  ('bistar kee chaadaren gandee hain','HI'),
  ('There is no hot water in my room','EN'),
  ('Não há água quente no meu quarto','PT'),
  ('मेरे कमरे में गर्म पानी नहीं हैूं','HI'),
  ('mere kamare mein garm paanee nahin hai','HI'),
  ('Where can I get some ice','EN'),
  ('Onde posso obter gelo','PT'),
  ('मुझे कुछ बर्फ कहां मिल सकती है','HI'),
  ('mujhe kuchh barph kahaan mil sakatee hai','HI'),
  ('The air conditioner is not working','EN'),
  ('O ar condicionado não está funcionando','PT'),
  ('एयर कंडीशनर काम नहीं कर रहा है','HI'),
  ('eyar kandeeshanar kaam nahin kar raha hai','HI'),
  ('I would like to check out','EN'),
  ('Gostaria de fazer check-out','PT'),
  ('मुझे चेक आउट करना है','HI'),
  ('mujhe chek aaut karana hai','HI'),
  ('May I try this on','EN'),
  ('Posso experimentar isso','PT'),
  ('क्या मैं इसे पहन कर देख सकता हूं','HI'),
  ('kya main ise pehen kar dekh sakata hoon','HI'),
  ('Can I pay by credit card','EN'),
  ('Posso pagar com cartão de crédito','PT'),
  ('क्या हम क्रेडिट कार्ड द्वारा भुगतान कर सकते हैं','HI'),
  ('kya ham kredit kaard dvaara bhugataan kar sakate hain','HI'),
  ('It’s too expensive','EN'),
  ('É muito caro','PT'),
  ('यह बहुत महंगा है','HI'),
  ('yah bahut mahanga hai','HI'),
  ('Is this your final price','EN'),
  ('Este é o seu preço final','PT'),
  ('क्या यह आपकी अंतिम कीमत है','HI'),
  ('kya yah aapakee antim keemat hai','HI'),
  ('I’ll take this one','EN'),
  ('Eu vou pegar esse aqui','PT'),
  ('मैं इसे लेना चाहता हूँ','HI'),
  ('main ise lena chaahata hun','HI'),
  ('Where is the cashier','EN'),
  ('Onde está o caixa','PT'),
  ('कैशियर कहाँ है','HI'),
  ('kaishiyar kahaan hai','HI'),
  ('Where can I change money','EN'),
  ('Onde posso trocar dinheiro','PT'),
  ('मैं पैसों का विनिमय कहां कर सकता हूं','HI'),
  ('main paison ka vinimay kahaan kar sakata hoon','HI'),
  ('Is there an ATM machine around here','EN'),
  ('Existe um caixa eletrônico por aqui','PT'),
  ('क्या आस पास एटीएम मशीन है','HI'),
  ('kya aas paas ATM masheen hai?','HI'),
  ('Are you sure','EN'),
  ('Você tem certeza','PT'),
  ('क्या आपको यकीन है','HI'),
  ('kya aapako yakeen hai','HI'),
  ('Are you used to the weather','EN'),
  ('Você está acostumado com o clima','PT'),
  ('क्या आप मौसम के अभ्यस्त हैं','HI'),
  ('kya aap mausam ke abhyast hain?','HI'),
  ('As far as I am concerned','EN'),
  ('Tanto quanto eu estou preocupado','PT'),
  ('जहाँ तक मेरा संबंध है','HI'),
  ('jahaan tak mera sambandh hai','HI'),
  ('Be careful with that','EN'),
  ('Tenha cuidado com isso','PT'),
  ('उससे सावधान रहें','HI'),
  ('usase saavadhaan rahen','HI'),
  ('By the way','EN'),
  ('A propósito','PT'),
  ('वैसे','HI'),
  ('vaise','HI'),
  ('Don’t worry','EN'),
  ('Não se preocupe','PT'),
  ('चिंता मत करो','HI'),
  ('chinta mat karo','HI'),
  ('Don’t panic','EN'),
  ('Não entre em pânico','PT'),
  ('घबराओ मत','HI'),
  ('ghabarao mat','HI'),
  ('Do you agree','EN'),
  ('Você concorda','PT'),
  ('क्या आप सहमत हैं','HI'),
  ('kya aap sahamat hain','HI'),
  ('Do you carry this in different sizes','EN'),
  ('Você carrega isso em tamanhos diferentes','PT'),
  ('क्या आपके पास इसके और साइज हैं ं','HI'),
  ('kya aapke paas eske aur sizes hain','HI'),
  ('Do you mind','EN'),
  ('Você se importa','PT'),
  ('अगर आपको परेशानी ना हो तो','HI'),
  ('agar aapako pareshaanee na ho to','HI'),
  ('Should we','EN'),
  ('Nós deveríamos','PT'),
  ('क्या हमेै','HI'),
  ('kya hamen','HI'),
  ('Help yourself','EN'),
  ('Fique a vontade','PT'),
  ('अपनी सहायता कीजिये','HI'),
  ('apanee sahaayata keejiye','HI'),
  ('How about you','EN'),
  ('E quanto a você','PT'),
  ('आप कैसे हैं','HI'),
  ('aap kaise hain','HI'),
  ('How come','EN'),
  ('Por quê','PT'),
  ('ऐसा कैसे','HI'),
  ('aisa kaise','HI'),
  ('How do you like it','EN'),
  ('Como é que você gosta?','PT'),
  ('तुम्हे यह कैसा लगा','HI'),
  ('tumhe yah kaisa laga','HI'),
  ('How long does it take','EN'),
  ('Quanto tempo leva','PT'),
  ('इसमें कितना समय लगता है','HI'),
  ('isamen kitana samay lagata hai','HI'),
  ('How often','EN'),
  ('Com que frequência','PT'),
  ('कितनी बार','HI'),
  ('kitanee baar','HI'),
  ('I bet','EN'),
  ('Eu aposto','PT'),
  ('मै शर्त लगाता होै','HI'),
  ('mai shart lagaata hu','HI'),
  ('I can hardly believe that','EN'),
  ('Eu mal posso acreditar nisso','PT'),
  ('मुझे शायद ही इस बात पर यकीन होै','HI'),
  ('mujhe shaayad hee is baat par yakeen ho','HI'),
  ('I can’t help','EN'),
  ('Não posso ajudar','PT'),
  ('मैं मदद नहीं कर सकता','HI'),
  ('main madad nahin kar sakata','HI'),
  ('I can’t say','EN'),
  ('Eu não posso dizer','PT'),
  ('मुझे नहीं पताा','HI'),
  ('mujhe nahi pata','HI'),
  ('I cannot wait','EN'),
  ('Eu não posso esperar','PT'),
  ('मैं इंतज़ार नहीं कर सकता','HI'),
  ('main intazaar nahin kar sakata','HI'),
  ('I have no idea','EN'),
  ('Eu não faço ideia','PT'),
  ('मुझे पता नहीं है','HI'),
  ('mujhe pata nahin hai','HI'),
  ('I have got to go.','EN'),
  ('Eu tenho que ir','PT'),
  ('पमुझे जाना होगा','HI'),
  ('mujhe jaana hoga','HI'),
  ('I’ll let you know','EN'),
  ('Eu aviso você','PT'),
  ('मैं आपको बता दूँगा।','HI'),
  ('main aapako bata doonga','HI'),
  ('I’d be grateful','EN'),
  ('Eu ficaria grato','PT'),
  ('मैं आभारी रहूँगा','HI'),
  ('main aabhaaree rahoonga','HI'),
  ('I’m afraid','EN'),
  ('Estou com medo','PT'),
  ('मुझे डर लग रहा है','HI'),
  ('mujhe dar lag raha hai','HI'),
  ('I’m looking forward to it','EN'),
  ('Estou ansioso para isso','PT'),
  ('मैं इसकी राह देख रहा हूं','HI'),
  ('main isakee raah dekh raha hoon','HI'),
  ('I’m not really happy with that','EN'),
  ('Eu não estou muito feliz com isso','PT'),
  ('मैं वास्तव में इससे खुश नहीं हूं','HI'),
  ('main vaastav mein isase khush nahin hoon','HI'),
  ('It’s my fault','EN'),
  ('É minha culpa','PT'),
  ('यह मेरी गलती है','HI'),
  ('yah meree galatee hai','HI')
