INSERT INTO Sentences
  (text, language_key)
VALUES
  ('What time is it','EN'),
  ('Que horas são','PT'),
  ('क्या समय हुआ है','HI'),
  ('kya samay hua hai','HI'),
  ('May I purchase headphones', 'EN'),
  ('Posso comprar fones de ouvido','PT'),
  ('क्या मैं हेडफ़ोन खरीद सकता हूँ','HI'),
  ('kya main hedafon khareed sakata hoon','HI'),
  ('May I have something to drink','EN'),
  ('Posso ter algo para beber','PT'),
  ('क्या मुझे कुछ पीने के लिए मिल सकता है','HI'),
  ('kya mujhe kuchh peena ke liye mil sakata hai','HI'),
  ('May I have something to eat','EN'),
  ('Posso comer alguma coisa','PT'),
  ('क्या मुझे कुछ खाने के लिए मिल सकता है?','HI'),
  ("kya mujhe kuchh khaane ke liye mil sakata hai",'HI'),
  ('Are meals included','EN'),
  ('As refeições estão incluídas','PT'),
  ('क्या भोजन शामिल हैं','HI'),
  ('kya bhojan shaamil hain','HI'),
  ('How much does the magazine cost', 'EN'),
  ('Quanto custa a revista','PT'),
  ('पत्रिका कितने की है','HI'),
  ('patrika kitney ki hai','HI'),
  ('Where is the restroom', 'EN'),
  ('Onde é o banheiro','PT'),
  ('शौचालय कहाँ है','HI'),
  ('shauchalya kahaan hai?','HI'),
  ('Where is my gate','EN'),
  ('Onde está o meu portão','PT'),
  ('मेरा गेट कहाँ है','HI'),
  ('mera get kahaan hai','HI'),
  ('What airline am I flying','EN'),
  ('Qual companhia aérea estou voando','PT'),
  ('मैं किस एयरलाइन की उड़ान भर रहा हूं','HI'),
  ('main kis eyaralain kee udaan bhar raha hoon','HI'),
  ('What time is my flight','EN'),
  ('A que horas é o meu voo','PT'),
  ('मेरी फ्लाइट का समय क्या है','HI'),
  ('meree flight ka samay kya hai','HI'),
  ('I would like some food','EN'),
  ('Eu gostaria de um pouco de comida','PT'),
  ('मुझे कुछ खाना चाहिए','HI'),
  ('mujhe kuchh khaana chaahie','HI'),
  ('How are you','EN'),
  ('Como você está','PT'),
  ('क्या हाल है','HI'),
  ('kya haal hai','HI'),
  ('How is it going','EN'),
  ('Como vão as coisas','PT'),
  ('कैसा चल रहा है','HI'),
  ('kaisa chal raha hai','HI'),
  ('Hello','EN'),
  ('Olá','PT'),
  ('नमस्तेे','HI'),
  ('namaste','HI'),
  ('Hi','EN'),
  ('Oi.','PT'),
  ('नमस्तेे','HI'),
  ('namaste','HI'),
  ('Hey','EN'),
  ('Ei','PT'),
  ('अरे','HI'),
  ('arey','HI'),
  ('Good morning','EN'),
  ('Bom Dia','PT'),
  ('शुभ प्रभात','HI'),
  ('shubh prabhaat','HI'),
  ('Good afternoon','EN'),
  ('Boa tarde','PT'),
  ('नमस्कार','HI'),
  ('namaskaar','HI'),
  ('Good evening','EN'),
  ('Boa noite','PT'),
  ('सुसंध्या','HI'),
  ('susandhya','HI'),
  ('Good night','EN'),
  ('Boa noite','PT'),
  ('शुभ रात्रिूं','HI'),
  ('shubh raatri','HI'),
  ('I love the feeling of fingers running through my hair','EN'),
  ('Eu adoro Cafuné','PT'),
  ('मुझे अपने बालों में उंगलियां चलाने का एहसास बहुत पसंद है','HI'),
  ('mujhe apane baalon mein ungaliyaan chalaane ka ehasaas bahut pasand hai','HI'),
  ('You hit one out of the park','EN'),
  ('Você foi ótimo','PT'),
  ('तुमने बहुत अच्छा किया','HI'),
  ('tumne bahut achchha kiya','HI'),
  ('You did great','EN'),
  ('Você foi ótimo','PT'),
  ('तुमने बहुत अच्छा किया','HI'),
  ('tumne bahut achchha kiya','HI'),
  ('Where is tourist information','EN'),
  ('Onde está a informação turística','PT'),
  ('पर्यटकों की जानकारी कहां हैै','HI'),
  ('paryatakon kee jaanakaaree kahaan hai','HI'),
  ('Where can I get my baggage','EN'),
  ('Onde posso obter a minha bagagem','PT'),
  ('मुझे अपना सामान कहां पर मिलेगा','HI'),
  ('mujhe apana saamaan kahaan par milega','HI'),
  ('I have to catch a connecting flight','EN'),
  ('Eu tenho que pegar um vôo de conexão','PT'),
  ('मुझे कनेक्टिंग फ्लाइट पकड़नी है','HI'),
  ('mujhe kanekting phlait pakadanee hai','HI'),
  ('Which way is that','EN'),
  ('Qual é o caminho','PT'),
  ('कौन सा तरीका है','HI'),
  ('kaun sa tareeka hai','HI'),
  ('I just missed my connecting flight','EN'),
  ('Eu perdi meu voo de conexão','PT'),
  ('मेरी कनेक्टिंग फ्लाइट छूट गयी ','HI'),
  ('meri connecting flight chhut gayi','HI'),
  ('Excuse me, Where is this boarding gate','EN'),
  ('Com licença, onde está esse portão de embarque','PT'),
  ('माफ कीजिए, यह बोर्डिंग गेट कहां है','HI'),
  ('maaph keejie, yah bording get kahaan hai','HI'),
  ('Can you recommend a hotel','EN'),
  ('Você pode recomendar um hotel','PT'),
  ('क्या आप होटल की सिफारिश कर सकते हैं','HI'),
  ('kya aap hotal kee siphaarish kar sakate hain','HI'),
  ('Is there a smoking area','EN'),
  ('Existe uma área para fumantes','PT'),
  ('क्या कोई धूम्रपान क्षेत्र है','HI'),
  ('kya koee dhoomrapaan kshetr hai','HI'),
  ('Is there a bus to the city','EN'),
  ('Existe um ônibus para a cidade','PT'),
  ('क्या शहर के लिए कोई बस है','HI'),
  ('kya shahar ke liye koi bas hai?','HI'),
  ('Where is the taxi stand','EN'),
  ('Onde fica o ponto de táxi','PT'),
  ('टैक्सी स्टैंड कहां है','HI'),
  ('taiksee staind kahaan hai?','HI'),
  ('Could you recommend a hotel in downtown','EN'),
  ('Você poderia recomendar um hotel no centro da cidade','PT'),
  ('आप शहर में एक अच्छा होटल बता सकते है','HI'),
  ('aap shahar mein ek achchha hotel bata sakate hain?','HI'),
  ('How much does it cost to take a taxi to this address','EN'),
  ('Quanto custa pegar um táxi para esse endereço','PT'),
  ('इस पते पर टैक्सी लेने में कितना खर्च होता है','HI'),
  ('is pate par taiksee lene mein kitana kharch hota hai','HI'),
  ('Take me to this address, please','EN'),
  ('Leve-me até este endereço por favor','PT'),
  ('कृपया मुझे इस पते पर ले चलिए','HI'),
  ('krpaya mujhe is pate par le chalie','HI'),
  ('Hilton hotel, please','EN'),
  ('Hotel Hilton, por favor','PT'),
  ('कृपया हिल्टन होटल चलिए','HI'),
  ('krpaya hiltan hotal chalie','HI'),
  ('Let me off here','EN'),
  ('Me deixe sair daqui','PT'),
  ('मुझे यहाँ छोड़ दोै','HI'),
  ('mujhe yahaan chhod do','HI'),
  ('Anywhere around here is fine','EN'),
  ('Qualquer lugar por aqui está bem','PT'),
  ('यहां आसपास कहीं भी ठीक है','HI'),
  ('yahaan aasapaas kaheen bhee theek hai','HI'),
  ('Keep the change','EN'),
  ('Fique com o troco','PT'),
  ('छुट्टे रख लो','HI'),
  ('chhutte rakh lo','HI'),
  ('I would like to book a room','EN'),
  ('Eu gostaria de reservar um quarto','PT'),
  ('मैं एक कमरा बुक करना चाहूंगा','HI'),
  ('main ek kamara buk karana chaahoonga','HI'),
  ('I’d like a single room','EN'),
  ('Gostaria de um quarto individual','PT'),
  ('मुझे एक सिंगल कमरा चाहिएूै','HI'),
  ('mujhe ek singal kamara chaahie','HI'),
  ('I’d like to book a double room for 3 nights','EN'),
  ('Eu gostaria de reservar um quarto duplo por 3 noites','PT'),
  ('मैं 3 रातों के लिए एक डबल कमरा बुक करना चाहता हूँ','HI'),
  ('main 3 raaton ke lie ek dabal kamara buk karana chaahata hoon','HI'),
  ('How much is a double room per night','EN'),
  ('Quanto custa um quarto duplo por noite','PT'),
  ('प्रति रात एक डबल कमरे का कितना है','HI'),
  ('prati raat ek dabal kamarey ka kitana hai?','HI'),
  ('I’d like a room with a nice view','EN'),
  ('Eu gostaria de um quarto com uma bela vista','PT'),
  ('मुझे एक अच्छे नज़ारा वाला कमरा चाहिए','HI'),
  ('mujhe ek achchhe nazarey wala kamara chaahie','HI'),
  ('Can I have an extra bed for my room','EN'),
  ('Posso ter uma cama extra no meu quarto','PT'),
  ('क्या मुझे अपने कमरे के लिए एक अतिरिक्त बिस्तर मिल सकता है','HI'),
  ('kya mujhe apane kamare ke lie ek atirikt bistar mil sakata hai','HI'),
  ('I’m arriving late. Please keep my reservation','EN'),
  ('Estou chegando atrasado. Por favor, mantenha minha reserva','PT'),
  ('मैं देर से पहुँच रहा हूँ कृपया मेरा  रिजर्वेशन रखें।','HI'),
  ('main der se pahunch raha hoon krpaya mera reservation rakhen.','HI'),
  ('When does the dining-room open','EN'),
  ('Quando a sala de jantar abre','PT'),
  ('भोजन कक्ष कब खुलता है?','HI'),
  ('bhojan kaksh kab khulata hai','HI'),
  ('When is breakfast served','EN'),
  ('Quando o café da manhã será servido','PT'),
  ('नाश्ता कब पेश किया जाता है','HI'),
  ('naashta kab pesh kiya jaata hai','HI'),
  ('Where can I keep my valuables','EN'),
  ('Onde posso guardar meus objetos de valor','PT'),
  ('मैं अपना कीमती सामान कहाँ रख सकता हूँ','HI'),
  ('main apana keematee saamaan kahaan rakh sakata hoon?','HI')
