INSERT INTO Sentences
  (text, language_key)
VALUES
  ('It’s on the tip of my tongue','EN'),
  ('Está na ponta da língua','PT'),
  ('यह मुझे जबानी याद है','HI'),
  ('yah mujhe jabaanee yaad hai','HI'),
  ('It’s up to you', 'EN'),
  ('Você decide','PT'),
  ('यह आप पर निर्भर करता हैा','HI'),
  ('yah aap par nirbhar karata hai','HI'),
  ('It’s your turn','EN'),
  ('É sua vez','PT'),
  ('यह आपकी बारी है','HI'),
  ('yah aapakee baaree hai','HI'),
  ('It may surprise you','EN'),
  ('Pode te surpreender','PT'),
  ('यह आपको आश्चर्यचकित कर सकता हैै','HI'),
  ("yah aapako aashcharyachakit kar sakata hai",'HI'),
  ('I’ve had enough','EN'),
  ('Eu já tive o suficient','PT'),
  ('मैंने बहुत कियाैं','HI'),
  ('mainne bahut kiya','HI'),
  ('On the other hand', 'EN'),
  ('Por outro lado','PT'),
  ('दूसरी ओरै','HI'),
  ('doosaree ore','HI'),
  ('See that', 'EN'),
  ('Veja isso','PT'),
  ('देखा','HI'),
  ('dekha','HI'),
  ('There is nothing I like better','EN'),
  ('Não há nada que eu goste melhor','PT'),
  ('ऐसा कुछ नहीं है जो मुझे बेहतर लगे','HI'),
  ('aisa kuchh nahin hai jo mujhe behatar lage','HI'),
  ('We might as well','EN'),
  ('Nós também podemos','PT'),
  ('हम भी शायद।','HI'),
  ('ham bhee shaayad','HI'),
  ('What can I do for you','EN'),
  ('O que posso fazer para você','PT'),
  ('मै आप के लिये क्य कर सकता हु','HI'),
  ('mai aap ke liye ky kar sakta hun','HI'),
  ('What do you say','EN'),
  ('O que você disse','PT'),
  ('आप क्या कहते हैं','HI'),
  ('aap kya kahate hain','HI'),
  ('What’s your favorite','EN'),
  ('Qual é o seu favorito','PT'),
  ('आपका पसंदीदा क्या है','HI'),
  ('aapaka pasandeeda kya hai?','HI'),
  ('He is ill in bed','EN'),
  ('Ele está doente na cama','PT'),
  ('वह अभी भी बिस्तर में है।','HI'),
  ('vah abhi bhi bistar mein hai.','HI'),
  ('I like ice-cream','EN'),
  ('Eu gosto de sorvete','PT'),
  ('मुझे आइसक्रीम पसंद है','HI'),
  ('mujhe aaisakreem pasand hai','HI'),
  ('I love this game','EN'),
  ('Eu amo este jogo','PT'),
  ('मुझे यह खेल पसंद है','HI'),
  ('mujhe yeh khel pasand hai','HI'),
  ('I’ll try my best','EN'),
  ('Eu vou tentar o meu melhor','PT'),
  ('मैं पूरी कोशिश करूंगा ','HI'),
  ('main pooree koshish karoonga','HI'),
  ('I’m on your side','EN'),
  ('Estou no seu lado','PT'),
  ('मैं तुम्हारी तरफ़ हूं','HI'),
  ('main tumhaaree taraf hoon','HI'),
  ('Easy come, easy go','EN'),
  ('Assim como vem, também vai','PT'),
  ('जो आसानी से मिलता है वो आसानी से चला भी जाता है','HI'),
  ('jo aasaanee se milata hai vo aasaanee se chala bhee jaata hai','HI'),
  ('I’ll check it out','EN'),
  ('Eu vou dar uma olhada','PT'),
  ('ममैं इसे देख लूँगा','HI'),
  ('main ise dekh loonga','HI'),
  ('It’s a long story','EN'),
  ('É uma longa história','PT'),
  ('क्यह एक लंबी कहानी है','HI'),
  ('yah ek lambee kahaanee hai','HI'),
  ('That’s all I need','EN'),
  ('Isso é tudo que preciso','PT'),
  ('मुझे यही सब चाहिए','HI'),
  ('mujhe yahee sab chaahie.','HI'),
  ('The view is great','EN'),
  ('A vista é ótima','PT'),
  ('दृश्य बहुत अच्छा है','HI'),
  ('drshy bahut achchha hai.','HI'),
  ('The walls have ears','EN'),
  ('As paredes têm ouvidos','PT'),
  ('दीवारों के कान हैै','HI'),
  ('deevaaron ke kaan hain','HI'),
  ('Here comes a bus','EN'),
  ('Aqui vem um ônibus','PT'),
  ('एक बस आ रही है','HI'),
  ('ek bas aa rahi hai','HI'),
  ('He is just a child','EN'),
  ('Ele é apenas uma criança','PT'),
  ('वह अभी बच्चा है','HI'),
  ('vah abhee bachcha hai','HI'),
  ('It seems all right','EN'),
  ('Parece tudo bem','PT'),
  ('यह सब ठीक लगता है','HI'),
  ('yah sab theek lagata hai','HI'),
  ('That’s a good idea','EN'),
  ('Essa é uma boa ideia','PT'),
  ('वह एक अच्छा विचार है','HI'),
  ('vah ek achchha vichaar hai','HI'),
  ('I am a football fan','EN'),
  ('Eu sou um fã de futebol','PT'),
  ('मैं एक फुटबॉल प्रशंसक हूं','HI'),
  ('main ek phutabol prashansak hoon','HI'),
  ('If only I could fly','EN'),
  ('Se eu pudesse voar','PT'),
  ('अगर मैं उड़ सकता है।','HI'),
  ('agar main ud sakata hai.','HI'),
  ('I’ll be right there','EN'),
  ('Eu estarei lá','PT'),
  ('मैं वहां मौजूद रहूंगा','HI'),
  ('main vahaan maujood rahoonga','HI'),
  ('Knowledge is power','EN'),
  ('Conhecimento é poder','PT'),
  ('ज्ञान ही शक्ति हैेै','HI'),
  ('gyaan hee shakti hai','HI'),
  ('We are good friends','EN'),
  ('Nós somos bons amigos','PT'),
  ('हम अच्छे मित्र हैे','HI'),
  ('ham achchhe mitr hain','HI'),
  ('He can’t take a joke','EN'),
  ('Ele não pode levar uma piada','PT'),
  ('वह मजाक नहीं ले सकता','HI'),
  ('vah majaak nahin le sakata.','HI'),
  ('It’s against the law','EN'),
  ('É contra a lei','PT'),
  ('यह कानून के विरूद्ध हैे','HI'),
  ('yah kaanoon ke virooddh hai','HI'),
  ('My mouth is watering','EN'),
  ('Estou ficando com água na boca','PT'),
  ('मेरे मुंह में पानी आ रहा है','HI'),
  ('mere munh mein paanee aa raha hai','HI'),
  ('Speak louder, please','EN'),
  ('Fale mais alto por favor','PT'),
  ('कृपया जोर से बाते करें','HI'),
  ('krpaya jor se baate karen','HI'),
  ('Speak slower, please','EN'),
  ('Falar mais devagar, por favor','PT'),
  ('कृपया धीरे - धीरे बोलिए','HI'),
  ('krpaya dheere - dheere bolie','HI'),
  ('I will be more careful','EN'),
  ('Eu serei mais cuidadoso','PT'),
  ('मैं और ध्यानपूर्वक रहूँगा','HI'),
  ('मmain aur dhyaanapoorvak rahoonga','HI'),
  ('I will never forget it','EN'),
  ('Eu nunca esquecerei','PT'),
  ('मैं इसे कभी नहीं भूल पाउंगा','HI'),
  ('main ise kabhee nahin bhool paunga','HI'),
  ('It is just what I need','EN'),
  ('É exatamente o que eu preciso','PT'),
  ('यह वही है जो मुझे चाहिए','HI'),
  ('yah vahee hai jo mujhe chaahie','HI'),
  ('Let bygones be bygones','EN'),
  ('Esquecer o passado','PT'),
  ('जो हो गया सो हो गया','HI'),
  ('jo ho gaya so ho gaya','HI'),
  ('Great minds think alike','EN'),
  ('Mentes brilhantes pensam igual','PT'),
  ('बड़े मन वाले ऐसा सोचते हैं','HI'),
  ('bade man vaale aisa sochate hain','HI'),
  ('I walked across the park','EN'),
  ('Eu atravessei o parque','PT'),
  ('मैं पार्क भर में चला गया','HI'),
  ('main paark bhar mein chala gaya','HI'),
  ('I’ll just play it by ear','EN'),
  ('Eu apenas tocarei de ouvido','PT'),
  ('विकसित होने के साथ ही स्थिति से निपट लूंगा','HI'),
  ('viksit hone ke sath stithi se nipat loonga','HI'),
  ('I’m not sure I can do it','EN'),
  ('Não tenho certeza se posso fazer isso','PT'),
  ('मुझे नहीं पता कि मैं यह कर सकता हूं','HI'),
  ('mujhe nahin pata ki main yah kar sakata hoon','HI'),
  ('I’m not used to drinking','EN'),
  ('Eu não estou acostumado a beber','PT'),
  ('ममुझे पीने की आदत नहीं है','HI'),
  ('mujhe peene kee aadat nahin hai','HI'),
  ('Let’s not waste our time.','EN'),
  ('Não vamos perder nosso tempo','PT'),
  ('हमें अपना समय बरबाद नहीं करना चाहिये','HI'),
  ('hamen apana samay barabaad nahin karana chaahiye','HI'),
  ('Stop making noise','EN'),
  ('Pare de fazer barulho','PT'),
  ('शोर करना बंद करो','HI'),
  ('shor karana band karo','HI'),
  ('That makes no difference','EN'),
  ('Isso não faz diferença','PT'),
  ('इससे कोई फर्क नहीं पड़ता','HI'),
  ('isase koee phark nahin padata','HI'),
  ('The price is reasonable','EN'),
  ('O preço é razoável','PT'),
  ('कीमत वाजिब हैै','HI'),
  ('keemat vaajib hai','HI'),
  ('I have a surprise for you','EN'),
  ('Eu tenho uma surpresa para você','PT'),
  ('मेरे पास तुम्हारे लिए एक सरप्राइज है','HI'),
  ('mere paas tumhaare lie ek sarapraij hai','HI'),
  ('I’ll have an appetizer','EN'),
  ('Eu terei um aperitivo','PT'),
  ('में क्षुधावर्धक लूंगा','HI'),
  ('mein kshudavardhak lunga','HI')
